/// <reference types="node" />
/**
 * Writes data/synthetic/roster.json — the fictional people (FR-037, FR-039) — from
 * data/synthetic/people_pool.json and office_activation.json. Deterministic, so the committed
 * file can be regenerated byte-for-byte; the roster is an INPUT to the fleet generator and is
 * committed so it can be reviewed (FR-003) and so datasets are reproducible.
 *
 *   node node_modules/vite-node/vite-node.mjs scripts/synthetic/authoring/make-roster.ts [--reference-as-of 2026-09-02]
 *
 * Rules: technician headcount follows the anchors in people_pool.json; one administrator per office
 * from its activation date, a second for Ottawa and Toronto from 2016; tenure is exponential
 * (mean 8 years, minimum 1) so custodianship turns over; one technician is guaranteed to leave
 * about 230 days before the reference as-of so the "leaver still holding equipment" scenario has a
 * candidate. FR-003: refuses any generated full name or family name that appears in the source
 * registry's Staff column.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { readCsv, SOURCE_REGISTRY, SYNTHETIC_INPUTS, type OfficeActivation, type RosterEntry } from "../lib/config";
import { Rng } from "../lib/rng";
import { addDays } from "../lib/time";

interface PeoplePool {
  given: string[];
  family: string[];
  demo: RosterEntry[];
  headcount: { technicians: Record<string, number>; meanTenureYears: number; minTenureYears: number };
}

function interpolate(anchors: Record<string, number>, year: number): number {
  const pts = Object.entries(anchors).map(([y, n]) => [Number(y), n] as const).sort((a, b) => a[0] - b[0]);
  if (year <= pts[0][0]) return pts[0][1];
  if (year >= pts[pts.length - 1][0]) return pts[pts.length - 1][1];
  for (let i = 1; i < pts.length; i++) {
    if (year <= pts[i][0]) {
      const [y0, n0] = pts[i - 1];
      const [y1, n1] = pts[i];
      return n0 + ((n1 - n0) * (year - y0)) / (y1 - y0);
    }
  }
  return pts[pts.length - 1][1];
}

function main(): void {
  const argv = process.argv.slice(2);
  const refIdx = argv.indexOf("--reference-as-of");
  const referenceAsOf = refIdx >= 0 ? argv[refIdx + 1] : "2026-09-02";
  const pool = JSON.parse(readFileSync(path.join(SYNTHETIC_INPUTS, "people_pool.json"), "utf8")) as PeoplePool;
  const offices = JSON.parse(readFileSync(path.join(SYNTHETIC_INPUTS, "office_activation.json"), "utf8")) as OfficeActivation;
  const rng = new Rng("englobe-ams-007/roster");

  const forbiddenFull = new Set<string>();
  const forbiddenFamily = new Set<string>();
  if (existsSync(SOURCE_REGISTRY)) {
    const rows = readCsv(SOURCE_REGISTRY);
    const idx = rows[0].indexOf("Staff");
    for (const r of rows.slice(1)) {
      const s = (r[idx] ?? "").trim();
      if (!s) continue;
      forbiddenFull.add(s.toLowerCase());
      const parts = s.split(/\s+/);
      if (parts.length > 1) forbiddenFamily.add(parts[parts.length - 1].toLowerCase());
    }
  }

  const used = new Set<string>();
  const roster: RosterEntry[] = [...pool.demo];
  for (const d of pool.demo) used.add(d.displayName.toLowerCase());
  const newPerson = (office: string, role: RosterEntry["role"], start: string): RosterEntry => {
    for (let i = 0; i < 1000; i++) {
      const given = rng.pick(pool.given);
      const family = rng.pick(pool.family);
      const full = `${given} ${family}`;
      if (used.has(full.toLowerCase()) || forbiddenFull.has(full.toLowerCase()) || forbiddenFamily.has(family.toLowerCase())) continue;
      used.add(full.toLowerCase());
      const upn = `${given}.${family}`.toLowerCase().replace(/[^a-z.-]/g, "") + "@englobecorp.com";
      const tenureYears = Math.max(pool.headcount.minTenureYears, rng.exp(pool.headcount.meanTenureYears));
      const end = addDays(start, Math.round(tenureYears * 365.25));
      return { upn, displayName: full, office, role, start, end: end > referenceAsOf ? null : end };
    }
    throw new Error("name pool exhausted");
  };

  const firstYear = Number(offices.offices.map((o) => o.activeFrom).sort()[0].slice(0, 4));
  const lastYear = Number(referenceAsOf.slice(0, 4));

  // administrators: per office from activation (+1 for Ottawa/Toronto from 2016), replaced when they leave
  for (const o of offices.offices) {
    const seats = o.name === "Ottawa" || o.name === "Toronto" ? [o.activeFrom, "2016-01-04"] : [o.activeFrom];
    for (const seatStart of seats) {
      let start = seatStart;
      while (start <= referenceAsOf) {
        if (o.name === "Ottawa" && seatStart === o.activeFrom && start < "2014-06-02") {
          // the demo admin (Alex Admin) fills Ottawa's first seat from 2014-06-02
          const p = newPerson(o.name, "OfficeAdmin", start);
          p.end = "2014-06-02";
          roster.push(p);
          start = "2014-06-02";
          break;
        }
        const p = newPerson(o.name, "OfficeAdmin", start);
        roster.push(p);
        if (p.end === null) break;
        start = addDays(p.end, rng.int(7, 45));
      }
    }
  }

  // technicians: hire to the headcount anchors, weighted by office share among active offices
  const activeTechs: RosterEntry[] = [];
  let forcedLeaverDone = false;
  for (let y = firstYear; y <= lastYear; y++) {
    for (let m = 1; m <= 12; m++) {
      const date = `${y}-${String(m).padStart(2, "0")}-${String(rng.int(2, 26)).padStart(2, "0")}`;
      if (date > referenceAsOf) break;
      // leavers
      for (let i = activeTechs.length - 1; i >= 0; i--) if (activeTechs[i].end !== null && activeTechs[i].end! <= date) activeTechs.splice(i, 1);
      const target = Math.round(interpolate(pool.headcount.technicians, y + (m - 1) / 12));
      const demoTechActive = pool.demo.filter((d) => d.role === "FieldUser" && d.start <= date).length;
      while (activeTechs.length + demoTechActive < target) {
        const active = offices.offices.filter((o) => o.activeFrom <= date);
        const office = rng.weighted(active.map((o) => [o.name, o.share] as const));
        const p = newPerson(office, "FieldUser", date);
        if (!forcedLeaverDone && date >= addDays(referenceAsOf, -365 * 6) && p.end === null) {
          p.end = addDays(referenceAsOf, -230);
          forcedLeaverDone = true;
        }
        roster.push(p);
        activeTechs.push(p);
      }
    }
  }

  roster.sort((a, b) => (a.start < b.start ? -1 : a.start > b.start ? 1 : a.upn < b.upn ? -1 : 1));
  const out = path.join(SYNTHETIC_INPUTS, "roster.json");
  writeFileSync(out, JSON.stringify(roster, null, 2) + "\n", "utf8");
  const techs = roster.filter((r) => r.role === "FieldUser");
  const admins = roster.filter((r) => r.role === "OfficeAdmin");
  console.log(`roster: ${roster.length} people (${techs.length} technicians, ${admins.length} administrators, ${roster.length - techs.length - admins.length} other); ${roster.filter((r) => r.end === null).length} active at ${referenceAsOf}; ${forbiddenFull.size} real staff names excluded -> ${out}`);
}

main();
