/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Source of truth: data/reference/state_machine.json
 * Generated by:    app/scripts/generate-state-machine.mjs (`npm run generate:state-machine`)
 *
 * Constitution Principle V (invalid transitions refused at every layer) and Principle VI (one
 * definition, two consumers): this is the app's copy of the transition matrix. The other
 * consumer is solution/flows/F1/definition.json, which is built from the same JSON so the two
 * can never drift — see solution/flows/F1/README.md for how it stays in step.
 *
 * Regenerate after editing the JSON: `npm run generate:state-machine`.
 */

export type AssetStatus = "Available" | "CheckedOut" | "Deployed" | "InCalibration" | "NeedsRepair" | "Missing" | "Retired";

export type TransactionType =
  | "AddToInventory"
  | "Audit"
  | "Checkout"
  | "Deploy"
  | "Found"
  | "MarkMissing"
  | "RepairComplete"
  | "ReportFault"
  | "Retire"
  | "Return"
  | "ReturnFromCalibration"
  | "SendToCalibration"
  | "Transfer"
  | "Undeploy";

export const STATUSES: readonly AssetStatus[] = [
  "Available",
  "CheckedOut",
  "Deployed",
  "InCalibration",
  "NeedsRepair",
  "Missing",
  "Retired"
] as const;

/** rows = current status, keys = transaction type, value = resulting status. Missing key = not allowed. */
export const STATE_MACHINE: Readonly<
  Record<AssetStatus, Partial<Record<TransactionType, AssetStatus>>>
> = {
  "Available": {
    "Checkout": "CheckedOut",
    "Transfer": "Available",
    "Deploy": "Deployed",
    "SendToCalibration": "InCalibration",
    "ReportFault": "NeedsRepair",
    "MarkMissing": "Missing",
    "Retire": "Retired",
    "Audit": "Available",
    "AddToInventory": "Available"
  },
  "CheckedOut": {
    "Return": "Available",
    "Transfer": "CheckedOut",
    "Deploy": "Deployed",
    "ReportFault": "NeedsRepair",
    "MarkMissing": "Missing",
    "Audit": "CheckedOut"
  },
  "Deployed": {
    "Return": "Available",
    "Undeploy": "CheckedOut",
    "ReportFault": "NeedsRepair",
    "MarkMissing": "Missing",
    "Audit": "Deployed"
  },
  "InCalibration": {
    "ReturnFromCalibration": "Available",
    "ReportFault": "NeedsRepair",
    "Retire": "Retired",
    "Audit": "InCalibration"
  },
  "NeedsRepair": {
    "SendToCalibration": "InCalibration",
    "RepairComplete": "Available",
    "Retire": "Retired",
    "Audit": "NeedsRepair"
  },
  "Missing": {
    "Found": "Available",
    "Retire": "Retired",
    "Audit": "Missing"
  },
  "Retired": {
    "Audit": "Retired"
  }
} as const;
